### ISSUE TITLE
Internal server error for weather_adj and weather_level_adj

### ISSUE THREAD

**Issue by davidhrbaty** [Dan-in-CA/sip_plugins#11]
Hi Dan,

I installed to ospi weather_adj and weather_level_adj plugins, but I have problem with it. I get "Internal server error" in web browser and there is a trace from console:

```
Traceback (most recent call last):
  File "/home/pi/OSPi/web/application.py", line 239, in process
    return self.handle()
  File "/home/pi/OSPi/web/application.py", line 230, in handle
    return self._delegate(fn, self.fvars, args)
  File "/home/pi/OSPi/web/application.py", line 423, in _delegate
    return handle_class(cls)
  File "/home/pi/OSPi/web/application.py", line 399, in handle_class
    return tocall(*args)
  File "/home/pi/OSPi/plugins/weather_adj.py", line 155, in GET
    return template_render.weather_adj(get_weather_options())
  File "/home/pi/OSPi/web/template.py", line 1020, in template
    return self._base(t(*a, **kw))
  File "/home/pi/OSPi/web/template.py", line 881, in __call__
    return BaseTemplate.__call__(self, *a, **kw)
  File "/home/pi/OSPi/web/template.py", line 808, in __call__
    return self.t(*a, **kw)
  File "templates/weather_adj.html", line 37, in __template__
    <td style='text-transform: none;'>$_('Weather Provider'):</td>
KeyError: 'delay_duration'
```

Can you help me, where can I find a problem?
Thank you.

**Comment by davidhrbaty** [comment]
Hello Dan,

Can you help me with my problem? Do you need something else to solve the problem?


Thank you

**Comment by Dan-in-CA** [comment]
Hi David,
I will take a look. 
I have been working on a related project and it has been taking up a lot of my time.

**Comment by Dan-in-CA** [comment]
I installed both plugins on my test system but I did not get the error.

From the trace you provided it would seem there is a conflict between the two plugins. The delay_duration key points to a data list that is used by both plugins.

The "weather-based water level" plugin was made from the "Weather-based Rain Delay" plugin and uses a lot of the same code. Those plugins were written by two different authors.

Have you tried using just one of the plugins at a time?   I will do some more testing but if you can provide any more information about when the error occurs it would be very helpful.

Maybe the plugins need to run a while before the error happens?

**Comment by davidhrbaty** [comment]
Hi Dan,

Thank you, for your answer. I tried to remove "Weather-based Rain Delay" plugin, but result is the same.  All is well until I click on plugins and select "Weather-based water level". I get in my browser only "Internal server error".

There is traceback from console:
```
Traceback (most recent call last):
  File "/home/pi/OSPi/web/application.py", line 239, in process
    return self.handle()
  File "/home/pi/OSPi/web/application.py", line 230, in handle
    return self._delegate(fn, self.fvars, args)
  File "/home/pi/OSPi/web/application.py", line 423, in _delegate
    return handle_class(cls)
  File "/home/pi/OSPi/web/application.py", line 399, in handle_class
    return tocall(*args)
  File "/home/pi/OSPi/plugins/weather_level_adj.py", line 165, in GET
    return template_render.weather_level_adj(options_data())
  File "/home/pi/OSPi/web/template.py", line 1020, in template
    return self._base(t(*a, **kw))
  File "/home/pi/OSPi/web/template.py", line 881, in __call__
    return BaseTemplate.__call__(self, *a, **kw)
  File "/home/pi/OSPi/web/template.py", line 808, in __call__
    return self.t(*a, **kw)
TypeError: __template__() takes no arguments (1 given)

10.0.20.1:39015 - - [31/Jul/2015 08:55:04] "HTTP/1.1 GET /lwa" - 500 Internal Server Error
```
Here is a list of plugins that I have currently installed:

```
__init__.pyc
email_adj.pyc
mobile_app.pyc
mqtt.pyc
notify_change.pyc
plugin_manager.pyc
proto.pyc
signaling_examples.pyc
system_update.pyc
weather_level_adj.pyc
```

And here is list of python packages, that I have currently installed on  debian:

```
idle-python2.7
idle-python3.2
libpython2.7
python
python-dbus
python-dbus-dev
python-gi
python-minimal
python-numpy
python-pifacecommon
python-pifacedigitalio
python-pip
python-pkg-resources
python-pygame
python-rpi.gpio
python-setuptools
python-smbus
python-support
python-tk
python2.6
python2.6-minimal
python2.7
python2.7-minimal
python3
python3-minimal
python3-numpy
python3-pifacecommon
python3-pifacedigital-scratch-handler
python3-pifacedigitalio
python3-rpi.gpio
python3-tk
python3.2
python3.2-minimal
```

Plugins are installed for several months, so I do not think that will be a problem in that it should be run for a while.
Have you any other advice, where can be a problem?

**Comment by Dan-in-CA** [comment]
What version of OSPi are you running? the latest is v 2.2.51
I noticed that you have the notify_change and mqtt plugins installed. those were used for testing some time back and are not now part of the available plugins. Unless you are using the mqtt plugin I would suggest disabling those. The automatic uninstall will probably not work for those.

I have an installation of the latest OSPi version with the same plugins you have (except notify_change and mqtt) and I still don't get any error. You might try re-installing the weather_level_adj plugin. If you get that to work, the weather_adj plugin should also work I think.

Let me know how it goes.
