### ISSUE TITLE
pulse_cct enabled conflicts with Manage Plugins - prevents startup

### ISSUE THREAD

**Issue by gdgeist** [Dan-in-CA/sip_plugins#13]
pulse_cct enabled conflicts with Manage Plugins - prevents startup
ERROR - Plugin Conflict: Pulse Circuit; /pls and  Manage Plugins; /plugins

**Comment by Dan-in-CA** [comment]
You can manually disable the pluse_cct plugin using the command line.
From the SIP directory issue the command:
<pre>sudo chmod -x plugins/pulse_cct.py</pre>

I will look into the cause of the problem. Thanks for reporting this.

**Comment by Dan-in-CA** [comment]
An updated rev of the pulse_cct plugin has been pushed to the repo. This should fix the problem.
Please re-install the plugin to get the fix.

**Comment by gdgeist** [comment]
Fixed - thanks.  I have to say things have been pretty rocky since about the revision that made the project SIP.  I had to delete the entire install and start from scratch to get it to work again.
