### ISSUE TITLE
Weather-based Water Level: Skipped wundergound data because of a parsing error for today

### ISSUE THREAD

**Issue by gdgeist** [Dan-in-CA/sip_plugins#14]
Weather-based Water Level:

Error:"Skipped wundergound data because of a parsing error for today"

3.1.27.  Raspbian - entirely up to date.
Plugins updated by a p
Updated the plugins and weather level not calculated based upon history (2mm rainfall a day after .71 inch by Wunderground history)

Uninstall/reinstall and historical showing now 10mm instead of 2mm (which is still far short of the history showing in Wunderground direct) but receive the error:"Skipped wundergound data because of a parsing error for today"

**Comment by Dan-in-CA** [comment]
Does the location box on the Options page have your correct location?
