### ISSUE TITLE
Starting a plugin

### ISSUE THREAD

**Issue by danfranks** [Dan-in-CA/sip_plugins#16]
Hi, I am interested in writing a plugin, possibly a few depending on how well the first one goes, and was wondering how exactly I use the proto plugin to get started?

I write code poorly in about dozen languages and am adding Python to the fold.  I figure this would be a good way to get started.  

The first plugin is just going to be a twitterbot basically.  @dfranks-house "Started watering the grass", "Stopped watering the grass", etc.  
The second plugin uses SIP to open and close my chicken coop doors.  
The third plugin uses SIP to trigger a zone based on a motion sensor to keep cats from pooping in my kids sand box and to keep the chickens out of the garden.

Two of those will involve relays, motors, voltage converters and whatnot but I figure other people are already doing things like that and I can adapt what had already been figured out.

**Comment by Dan-in-CA** [comment]
Hi Dan,
Your projects sound really interesting. It would be great if we could move the discussion to the SIP forum:
http://nosack.com/sipforum/index.php
That will allow a larger group of DIYers to participate.

As far a using the proto plugin, I need to write a "Getting Started' section for the plugins wiki. Your request is providing a kick in the butt to get it started.

I am also working on a related automation project that started as a way to add soil moisture sensors to SIP. It is based in information from a book "Real World Instrumentation With Python" which I highly recommend for anyone building this type of project. There is a chapter on Python which is the best introduction to the language I have seen.
http://shop.oreilly.com/product/9780596809577.do

Dan

**Comment by danfranks** [comment]
I signed up but my verification email is not coming through.  I checked the spam folder as well.  Once it does, I will move my question to the forums and we can pick up there.

**Comment by Dan-in-CA** [comment]
I just checked the forum and your account should be activated now.
The wiki topic on creating a plugin from the Proto plugin is almost ready. It should be up within the next few hours. I also remembered that there is some similar information in the proto plugin docs:
From the Plugins menu open the Proto Plugin then click the  HELP button near the top of the page.

**Comment by danfranks** [comment]
Cool, I can post now.  You can go ahead and delete this thread.  I have the twitter template setup (based on proto) and am adding signal monitoring right now.  :)
