### ISSUE TITLE
How to format MQTT messages for mqtt_schedule plugin

### ISSUE THREAD

**Issue by arlinjv** [Dan-in-CA/sip_plugins#26]
What is the format for the MQTT payload when activating zones via the mqtt_schedule plugin?

**Comment by Dan-in-CA** [comment]
From looking at the code for the plugin it looks like the payload should be a list of ones and zeros that matches the number of active stations in you system. For example:
[0, 1, 0,  0,  0, 0, 0, 0]
This should tun on station 2 of an 8 station system.

I have not tested this and will not have a chance to do so until later today.  I will let you know more after I have a chance to test.

**Comment by Dan-in-CA** [comment]
Tested and confirmed. The payload shown in the previous post does work.

**Comment by arlinjv** [comment]
Thanks! I'll give it a shot.

**Comment by arlinjv** [comment]
Tried it and it worked great. Thanks, again.
