### ISSUE TITLE
MQTT Plugin - No DOWN or DIED publishing ?

### ISSUE THREAD

**Issue by FulvioSpelta** [Dan-in-CA/sip_plugins#34]
Hi all,
I've installed the mqtt plugin and the mqtt zone bradcaster; configurations:
![image](https://user-images.githubusercontent.com/1832999/59145752-877c5080-89e8-11e9-84dc-09fdc05de40d.png)
![image](https://user-images.githubusercontent.com/1832999/59145759-94993f80-89e8-11e9-91ce-151e1d8600bc.png)

Monitoring the messages published using mqqt-spy i see that only the msg "UP" is published:
![image](https://user-images.githubusercontent.com/1832999/59145779-d9bd7180-89e8-11e9-8311-7e3abb5d6d54.png)

I've tried both:
- restarting SIP using web interface
- reboot the raspberry by console (sudo reboot)

A new "UP" msg is published after restart but no "DIED" (will message) nor "DOWN".
Any ideas ?
Thanks a lot

**Comment by Dan-in-CA** [comment]
Looking at the code for the mqtt plugin the only thing I see that might be preventing the "down" message would be if the atexit Python module is not being imported.

Can you try running Python from the command line and try importing atexit to see if it imports without any error.

Or if you use the command (without quotes) "systemctl status sip" on the command line it may show any error.

**Comment by FulvioSpelta** [comment]
Hi Dan, thanks for feedback. Here some tests:

**Test 1 - SIP service stopped - Start python and manually load etexit module - Ok**
```
pi@Caldaia:~$ python
Python 2.7.13 (default, Sep 26 2018, 18:42:22)
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import atexit
>>> 
```

**Test 2 - SIP service stopped - Start SIP manually then exit by ctrl-c - Ok**
```
pi@Caldaia:~/SIP$ sudo /usr/bin/python /home/pi/SIP/sip.py
Could not use git to determine version!
Could not use git to determine date of last commit!
MQTT publish UP
plugins loaded:
  mobile_app
  mqtt
  mqtt_zones
  plugin_manager
  relay_board
  weather_level_adj
http://0.0.0.0:80/
 Starting timing loop

Checking weather status...
Using 5 historical days, 5 forecast days and today in calculations.
Current temp in C    : 19.7
________________________________
Water per day         : 30.0mm
Water needed (6 days) : 143.6mm
Total rainfall        : 27.7mm
________________________________
Irrigation needed     : 100.0mm
Weather Adjustment    : 66.2%

^CMQTT publish DOWN
```

**Test 3 - SIP service stopped - Start SIP manually without right permission then exit by error - Ok**
```
pi@Caldaia:~/SIP$ /usr/bin/python sip.py
Could not use git to determine version!
Could not use git to determine date of last commit!
MQTT publish UP
plugins loaded:
  mobile_app
  mqtt
  mqtt_zones
  plugin_manager
  relay_board
  weather_level_adj
Starting timing loop
http://0.0.0.0:80/

Traceback (most recent call last):
  File "sip.py", line 258, in <module>
    app.run()
  File "sip.py", line 202, in run
    return web.httpserver.runsimple(func, (ip, port))
  File "/home/pi/SIP/web/httpserver.py", line 157, in runsimple
    server.start()
  File "/home/pi/SIP/web/wsgiserver/__init__.py", line 1753, in start
    raise socket.error(msg)
socket.error: No socket could be created
MQTT publish DOWN
```

**Test 4 - start and stop SIP service by systemd  - KO (no DOWN message)**
```
pi@Caldaia:~/SIP$ sudo service sip start
pi@Caldaia:~/SIP$ sudo service sip stop
pi@Caldaia:~/SIP$ sudo service sip status
● sip.service - SIP
   Loaded: loaded (/etc/systemd/system/sip.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Mon 2019-06-10 08:42:55 CEST; 25s ago
  Process: 15112 ExecStart=/usr/bin/python /home/pi/SIP/sip.py (code=killed, signal=TERM)
 Main PID: 15112 (code=killed, signal=TERM)

Jun 10 08:42:28 Caldaia systemd[1]: Started SIP.
Jun 10 08:42:55 Caldaia systemd[1]: Stopping SIP...
Jun 10 08:42:55 Caldaia systemd[1]: Stopped SIP.
```
**Test 5 - start SIP service and stop by kill command  - KO (no DOWN message)**
```
pi@Caldaia:~/SIP$ sudo service sip start
pi@Caldaia:~/SIP$ sudo ps -A -f | grep sip
root     15407     1  3 08:44 ?        00:00:00 /usr/bin/python /home/pi/SIP/sip.py
pi       15455 13353  0 08:44 pts/0    00:00:00 grep sip
pi@Caldaia:~/SIP$ sudo kill 15407
pi@Caldaia:~/SIP$ sudo ps -A -f | grep sip
pi       15527 13353  0 08:45 pts/0    00:00:00 grep sip
```
It seems somthing related to service execution (sorry I'm not a linux specialist)

**Comment by FulvioSpelta** [comment]
In this stackoverflow post i've found:

> Note: the functions registered via this module are not called when the program is killed by a signal, when a Python fatal internal error is detected, or when os._exit() is called.

[https://stackoverflow.com/questions/2546276/python-process-wont-call-atexit](https://stackoverflow.com/questions/2546276/python-process-wont-call-atexit)

**Comment by Dan-in-CA** [comment]
Interesting stackoverflow post.
The MQTT plugin already has a "will" starting at line 105:
`            if _settings['publish_up_down']:
                _client.will_set(_settings['publish_up_down'], json.dumps("DIED"), qos=1, retain=True)
            _client.loop_start()`

The solution in the stackoverflow post for capturing kill signals looks like it could help the plugin report on system down events. SIP normally runs under Linux so it shouldn't be a problem.

I will work on adding the signal capture code to the plugin and will post here when it has been updated. It looks like it will be fairly easy.

**Comment by Dan-in-CA** [comment]
Upon further investigation it appears that SIP and it's plugins being multi-threaded adds some complications at least under Python 2.7. SIP's restart function runs in a separate thread.

I will continue to work on this but it will probably take longer than I expected at first. SIP uses the "blinker" module for signalling between the main program and plugins. That may provide a solution.

**Comment by Dan-in-CA** [comment]
OK, I found a bug in the MQTT plugin.
The statement that sets the "will" was placed after the client connect statement. It must come before a connection is made.

It seems to be working now.  I posted an update to the SIP plugins repository.
Let me know if it works for you.

**Comment by FulvioSpelta** [comment]
Hi I confirm that the new version publish "DOWN" message both using service stop command and kill command.

Now you have a "UP" message when the system is running and a "DOWN" when not.
Thanks a lot I think that this feature is enought to effectively monitor the system status.

**Comment by Dan-in-CA** [comment]
Thanks for the confirmation.
Closing issue.
