### ISSUE TITLE
lcd_adj will not appear as an enabled plugin

### ISSUE THREAD

**Issue by gdgeist** [Dan-in-CA/sip_plugins#45]
on latest build 4.1.11, fresh install of Pi and SIP.  lcd_adj installed and enabled and not showing up in pull down window or directly accessible at /lcd url.

**Comment by Dan-in-CA** [comment]
I tried it here and the plugin appears in the Plugins drop-down and I was able to access the setup page.

How are you running SIP? 
If you started SIP from the command line you would need to stop and re-start sip. You may also need to refresh the browser page.

The other thing I would suggest is to re-install the plugin.

Let me know if you are still having the problem. 

Dan

**Comment by gdgeist** [comment]
Wiped and tried again this time only installing lcd_adj to start:
Heres what i got:

pi@raspberrypi:~ $ sudo python SIP/sip.py
Ignoring exception while loading the lcd_adj plug-in.
No module named builtins
Messge from Signaling plugin!: Just an example!
plugins loaded:
  mobile_app
  plugin_manager
  signaling_examples
  system_update
zones changed
Starting timing loop
[0
, 0, 0, 0, 0, 0, 0, A new day has started.
0]
http://:::80/


which i assume references:
`from __future__ import print_function
from builtins import range
from threading import Thread, Lock`

and in turn:
`if PY2:
    import __builtin__ as builtins
else:
    import builtins`

so since this is on 2.7 - i am going to bet you are on python 3.x.....

assume i can fix by switching to 3.x python

**Comment by gdgeist** [comment]
that was it.  changed to 3.x as preferred version of python and now works.  havent read your code enough to see why it fails on 2.x but if i get a chance i will

**Comment by Dan-in-CA** [comment]
Thanks for the feedback.
The builtins module was part of an automated system for making SIP Python 2 and 3 compatible.
http://python-future.org/automatic_conversion.html

I will take a look at the plugin.

Dan

**Comment by gdgeist** [comment]
Just a note - thanks for the work on this - sure u have other things to do with your time!

**Comment by Dan-in-CA** [comment]
After doing some quick tests (without an LCD attached to the Pi) it looks like the problem can be fixed by changing line 5 in lcd_adj.py from
`from builtins import range`
to
`from six.moves import range`

Dan

**Comment by gdgeist** [comment]
nice - will do

**Comment by gdgeist** [comment]
ok that fixes it.  FWIW using Python3 and was puzzled why LCD wouldnt update - you need to install  python3-rpi.gpio to work with python3. ;)
