### ISSUE TITLE
Absolute path in code

### ISSUE THREAD

**Issue by seventer** [Dan-in-CA/sip_plugins#59]
There is an absolute path in the code which makes the plugin not working if SIP is installed at another location.
https://github.com/Dan-in-CA/sip_plugins/blob/0eef03e42518310d219efddd836a4fc1e2b3b57b/flow/flow.py#L7

**Comment by Dan-in-CA** [comment]
Changed to:
sys.path.insert(0, './plugins/flowhelpers')
Tested and it works now.

**Comment by seventer** [comment]
Also tested and can confirm it's working fine.
Hopefully the original author (@IMHarris ) will update his own source as well.

**Comment by IMHarris** [comment]
Thanks @seventer for the fix. I'll update my code as well. Were you able to get the full system to work?

**Comment by Dan-in-CA** [comment]
Hey Ian,
I have been trying to contact you.
You can reach me at
dkimberling59@gmail.com

Dan

**Comment by seventer** [comment]
@IMHarris I have no flow sensor yet so I've tested with a Arduino Pro Mini, powered en connected from/to the RasPi with a rotary switch as a (manual) flow sensor.  It is doing something. While rotating I see milions of liters flowing :-)
Not sure what else the plugin is doing. @Dan-in-CA also want to discuss the functionality of this plugin. Maybe it is better to open a discussion on the SIP forum then.

**Comment by IMHarris** [comment]
Glad to hear the plugin is showing signs of life for you. Looking forward to discussing further.
